// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enversoft.Shared;

public partial class Logistics
{
    public int LogisticsId { get; set; }

    public string VehicleDescription { get; set; }

    public string VehicleNumberPlate { get; set; }

    public string FromString { get; set; }

    public int? WarehouseFromId { get; set; }

    public int? SupplierFromId { get; set; }

    public decimal? SupplierCost { get; set; }

    public int WarehouseDeliveryId { get; set; }

    public DateTime? WarehouseDispatchDate { get; set; }

    public DateTime? DateDelivered { get; set; }

    public DateTime? DueDate { get; set; }

    public virtual Supplier SupplierFrom { get; set; }

    public virtual Warehouse WarehouseDelivery { get; set; }

    public virtual Warehouse WarehouseFrom { get; set; }
}