// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enversoft.Shared;

public partial class Order
{
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime? DateFulfilled { get; set; }

    public DateTime DateCreated { get; set; }

    public Guid OrderReference { get; set; }

    public decimal VAT { get; set; }

    public decimal Subtotal { get; set; }

    public decimal GrandTotal { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<OrderItem> OrderItem { get; set; } = new List<OrderItem>();
}