// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enversoft.Shared;

public partial class StockItem
{
    public int StockItemId { get; set; }

    public string StockItemType { get; set; }

    public int? WarehouseId { get; set; }

    public int? SupplierId { get; set; }

    public int? LogisticsId { get; set; }

    public int ItemId { get; set; }

    public int? Quantity { get; set; }

    public virtual Item Item { get; set; }

    public virtual Logistics Logistics { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}