// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enversoft.Shared;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public int Code { get; set; }

    public string Name { get; set; }

    public string Telephone { get; set; }

    public virtual ICollection<Logistics> Logistics { get; set; } = new List<Logistics>();

    public virtual ICollection<SupplierLocation> SupplierLocation { get; set; } = new List<SupplierLocation>();
}