// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enversoft.Shared;

public partial class SupplierLocation
{
    public int SupplierLocationId { get; set; }

    public int SupplierId { get; set; }

    public string Address { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public virtual Supplier Supplier { get; set; }
}