// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enversoft.Shared;

public partial class Warehouse
{
    public int WarehouseId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public virtual ICollection<Logistics> LogisticsWarehouseDelivery { get; set; } = new List<Logistics>();

    public virtual ICollection<Logistics> LogisticsWarehouseFrom { get; set; } = new List<Logistics>();
}